name: Publish NuGet

on:
  release:
    types: [published]

# 1. ADD Permissions block to request the id-token
permissions:
  contents: read # Default needed for actions/checkout
  id-token: write # This is essential to retrieve the OIDC token

jobs:
  publish:
    # if: ${{ github.event.release.prerelease == false }} 
    runs-on: ubuntu-latest
    
    # 2. Add environment to meet your trusted publishing policy
    environment: production 
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Pack
        run: |
          VERSION=${{ github.event.release.tag_name }} 
          VERSION=${VERSION#v}
          dotnet pack Azure.Functions.DistributedLock/Azure.Functions.DistributedLock.csproj --configuration Release --no-build -p:PackageVersion=$VERSION -o artifacts
          
      # 3. STEP: Push using OIDC token
      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }} # Your NuGet.org username
    
      # Push the package
      - name: NuGet push
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json